### ISSUE TITLE
要怎么体现修改？结果好像并没有体现出来呀？

### ISSUE THREAD

**Issue by xiaoshengpapa** [MilkyBoat/RedactableBlockchain#1]
hello 运行的结果好像只有显示大小，要怎么样编辑链的内容呢

**Comment by MilkyBoat** [comment]
这个实现是把账本文本存在链下，把账本的变色龙哈希作为其签名存在链上。所以链上数据变化的只有变色龙哈希的陷门密钥r，它与变色龙哈希共同组成签名。之所以这样主要是考虑到，如果链上内容放账本明文，然后使用变色龙哈希替换以太坊哈希，不能防止不诚实节点不更新数据以抵抗链编辑。所以链上只有签名，账本明文通过第三方存储，用户通过第三方取回账本，到可以被编辑的链验证签名即可。

**Comment by MilkyBoat** [comment]
在这个实现中，只进行测试，所以账本明文就存储在本地，在/app/chainUtil.py:8 声明的全局变量chainData用于存放账本明文
